//ASKS INFORMATION TO BE ENTERED TO CREATE AN EVENT ON THE SELECTED DAY
//(SHOULD RESIDE IN ENLARGED DATE AS A BUTTON TO CREATE / ADD EVENTS AND REMOVE EVENTS)
//SHOULD BE ABLE TO CREATE A NEW EVENT OR EDIT AN EXISTING EVENT

function CreateEvent() {

}

export default CreateEvent;