// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3mtr4zT94qW_3azL4q8sEEUnMRdUHRs0',
    appId: '1:228632083486:web:56f73ba000519b500ec20f',
    messagingSenderId: '228632083486',
    projectId: 'calendarplusplus-a24d5',
    authDomain: 'calendarplusplus-a24d5.firebaseapp.com',
    storageBucket: 'calendarplusplus-a24d5.firebasestorage.app',
    measurementId: 'G-QFVZW4EV1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFtRzF0_j-pPAdII88IhAjC1-xKTeEM4',
    appId: '1:228632083486:android:575b10a3b020a2070ec20f',
    messagingSenderId: '228632083486',
    projectId: 'calendarplusplus-a24d5',
    storageBucket: 'calendarplusplus-a24d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZc_9iyP4eKR7QQG0-Wp8wQdmpi1GfgtU',
    appId: '1:228632083486:ios:0c758c8b84891d380ec20f',
    messagingSenderId: '228632083486',
    projectId: 'calendarplusplus-a24d5',
    storageBucket: 'calendarplusplus-a24d5.firebasestorage.app',
    iosBundleId: 'com.jonathan.calendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZc_9iyP4eKR7QQG0-Wp8wQdmpi1GfgtU',
    appId: '1:228632083486:ios:14b802ecf66f9b010ec20f',
    messagingSenderId: '228632083486',
    projectId: 'calendarplusplus-a24d5',
    storageBucket: 'calendarplusplus-a24d5.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3mtr4zT94qW_3azL4q8sEEUnMRdUHRs0',
    appId: '1:228632083486:web:7c3de2b2d93a966c0ec20f',
    messagingSenderId: '228632083486',
    projectId: 'calendarplusplus-a24d5',
    authDomain: 'calendarplusplus-a24d5.firebaseapp.com',
    storageBucket: 'calendarplusplus-a24d5.firebasestorage.app',
    measurementId: 'G-DTD0CDDS00',
  );
}
